import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Product Store",
  description: "Generated by create next app",
};

export default function DeviceLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body      >
        {children}
      </body>
    </html>
  );
}
